language: c
notifications:
  email: false

install:
  - MINICONDA=Miniconda3-latest-Linux-x86_64.sh
  - wget http://repo.continuum.io/miniconda/$MINICONDA
  - bash $MINICONDA -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - echo $PATH
  - which python && python --version

script:
  - mkdir -p tarballs data
  - (cd tarballs && cat ../anaconda_tarballs.txt | xargs -n1 -I '{}' sh -c "echo '{}'; wget -q https://repo.continuum.io/pkgs/free/linux-64/'{}'")
  - make -j2 all
  - cat unmet-depends.json
  - cat anaconda-depends.json

cache:
  directories:
    - tarballs/
